platform :ios, '8.0'

target 'DvrDirectConTool' do
  use_frameworks!
    pod 'Reachability', '~>3.2'
    pod 'SVProgressHUD', '~>2.2.5'
    pod 'Masonry', '~>1.1.0'
    pod 'Bugly', '~> 2.5.0'
    pod 'AFNetworking', '~>3.2.1'
    pod 'JMMonitorView'
    pod 'ZJLog'

end
